.pragma library

// The things on the other side.
//
// Blocky shaded faces in the same character vocabulary as the logo, so they
// belong to the same world rather than looking pasted in. Each is a soft
// halo of ░ falling off to a solid ██ core, with the eyes and mouth carved
// straight out to empty — negative space is what makes them read as faces at
// this size, and the halo is what keeps them reading as apparitions instead
// of stickers.
//
// Generated by scratchpad/faces.py from ellipse falloff, so every row is the
// same width. Hand-edit freely; just keep the rows rectangular or the
// GhostFaces layer will size them wrong.

var WATCHER = [
  "        ░░░░░░░░░░        ",
  "     ░░░░░░░░░░░░░░░░     ",
  "    ░░░░░▒▒▒▒▒▒▒▒░░░░░    ",
  "   ░░▒▒▓▓▓█▓▓▓▓█▓▓▓▒▒░░   ",
  "  ░░░▒    █▓██▓█    ▒░░░  ",
  "  ░░░      ████      ░░░  ",
  "  ░░░▒    ██████    ▒░░░  ",
  "  ░░░▒▒▓▓▓██████▓▓▓▒▒░░░  ",
  "  ░░░░▒▒▓▓▓▓██▓▓▓▓▒▒░░░░  ",
  "   ░░░░▒▒▒      ▒▒▒░░░░   ",
  "    ░░░░░▒▒▒  ▒▒▒░░░░░    ",
  "     ░░░░░░░░░░░░░░░░     ",
  "        ░░░░░░░░░░        "
]

var CALLER = [
  "         ░░░░░░░░         ",
  "       ░░░░░░░░░░░░       ",
  "      ░░░▒▒▒▒▒▒▒▒░░░      ",
  "     ░░░▒▒▒▓▓▓▓▒▒▒░░░     ",
  "    ░░░▒   ▓██▓   ▒░░░    ",
  "    ░░░     ██     ░░░    ",
  "    ░░▒▒   ████   ▒▒░░    ",
  "    ░░░▒▓▓██████▓▓▒░░░    ",
  "    ░░░▒▒▓▓▓  ▓▓▓▒▒░░░    ",
  "     ░░░▒▒▒    ▒▒▒░░░     ",
  "      ░░░▒▒    ▒▒░░░      ",
  "       ░░░░░░░░░░░░       ",
  "         ░░░░░░░░         "
]

var PRESSER = [
  "           ░░░░░░         ",
  "        ░░░░░░░░░░░░      ",
  "      ░░░░░▒▒▒▒▒▒░░░░░    ",
  "     ░▒▒▓▓▓▓▓▓▓▒▒▒▒░░░░   ",
  "    ░░▒    █▓▓▓▓▓▒▒▒░░░   ",
  "   ░░░      ████    ░░░   ",
  "   ░░░      ████    ░░░   ",
  "   ░░░▒   ██████▓▓▒▒░░░   ",
  "   ░░░▒▒▓▓▓███▓▓▓▒▒▒░░░   ",
  "   ░░░░▒▒▒      ▒▒░░░░    ",
  "    ░░░░▒▒     ▒▒░░░░     ",
  "     ░░░░░░░░░░░░░░       ",
  "        ░░░░░░░░░         "
]

var FACES = [
  { name: "watcher", lines: WATCHER },
  { name: "caller",  lines: CALLER  },
  { name: "presser", lines: PRESSER }
]

function count() {
  return FACES.length
}

function textAt(index) {
  var face = FACES[((index % FACES.length) + FACES.length) % FACES.length]
  return face.lines.join("\n")
}

function rows() {
  return FACES[0].lines.length
}

function columns() {
  return FACES[0].lines[0].length
}
